targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/gen/{{file}}.g.dart'
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false
      freezed:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/gen/{{file}}.f.dart'
          union_value_case: snake
          when: { when: false, whenOrNull: false, maybeWhen: false, }